#!/bin/bash

if [[ $1 =~ ^(ps|images)$ ]]; then
    docker "$@" | { less || more || cat; }
elif [[ $1 =~ ^(-h|--help)$ ]]; then
    echo -e "\n  -----\n"
    echo -e "  PULL, RUN AND SHELL INTO ALPINE\n    docker run alpine\n"
    echo -e "  DITTO AND MOUNT PWD\n    docker run . alpine\n"
    echo -e "  DITTO AND MORE\n    docker run . -p 8000:8000 -v \$PWD/.local/bin/somescript:/bin/somescript --name alpine-app alpine\n\n  -----"
    echo
    echo -e "  KILL AND REMOVE CONTAINER\n    docker rm alpine-app\n"
    echo -e "  DITTO AND REMOVE IMAGE\n    docker rm alpine-app alpine\n"
    echo -e "  REMOVE JUST AN IMAGE\n    docker rm - alpine\n\n  -----"
    echo
    echo -e "  VIEW COMMANDLOG\n    docker history\n"
    echo -e "  CLEAR COMMANDLOG\n    docker history -cw"
    echo -e "\n  -----\n"
    exit 0
elif [[ ! $1 =~ ^(history)$ ]]; then
    [ -z "$2" ] && echo "ERROR\n    no target specified" && exit 1
fi

if [[ $1 == "run" ]]; then
    mkdir -p $HOME/.local/dockerdo ; mkdir -p $HOME/.nano ; touch $HOME/.nanorc
    [[ $2 == "." ]] && remainder="-v $PWD:/app -w /app ${@:3}" || remainder="${@:2}"
    c_id=$(docker run -d -v "$HOME"/.nanorc:/root/.nanorc -v "${NANO_SYNTAX_DIR:-$HOME/.nano}":/root/.nano $remainder tail -f /dev/null)
    echo "echo $? && docker run -d -v $HOME/.nanorc:/root/.nanorc -v ${NANO_SYNTAX_DIR:-$HOME/.nano}:/root/.nano $remainder tail -f /dev/null" | tee -a ~/.local/dockerdo/history.txt
    if [[ $? -eq 0 ]]; then
        docker exec -it "$c_id" /bin/bash 2> /dev/null || docker exec -it "$c_id" /bin/sh
    else
        docker pull "$2" && dockerdo run "$2"
    fi
elif [[ $1 == "rm" ]]; then
    if [[ $2 != "-" ]]; then
        docker kill "$2" 2> /dev/null
        docker rm "$2" 2> /dev/null
    fi
    [ ! -z "$3" ] && docker rmi "$3"
elif [[ $1 == "history" ]]; then
    if [[ $2 == "-cw" ]]; then
        echo -n > $HOME/.local/dockerdo/history.txt
    else
        cat $HOME/.local/dockerdo/history.txt | { less || more || cat; }
    fi
else
    if [[ $1 == "inspect" ]]; then
        docker "$@" | { less || more || cat; }
    else
        docker "$@"
    fi
fi
