#!/bin/bash

[ -z "$2" ] && echo "ERROR : no target specified" && exit 1

if [[ $1 == "run" ]]; then
    mkdir -p $HOME/.poddo && mkdir -p $HOME/.nano && touch $HOME/.nanorc
    echo "podman run -d -v $HOME/.nanorc:/root/.nanorc -v ${NANO_SYNTAX_DIR:-$HOME/.nano}:/root/.nano ${@:2} tail -f /dev/null" | tee -a ~/.poddo/history.txt
    c_id=$(podman run -d -v "$HOME"/.nanorc:/root/.nanorc -v "${NANO_SYNTAX_DIR:-$HOME/.nano}":/root/.nano "${@:2}" tail -f /dev/null)
    [[ $? == 125 ]] && podman pull "docker.io/library/$2" && poddo run "$2"
    podman exec -it "$c_id" /bin/bash 2> /dev/null || podman exec -it "$c_id" /bin/sh
elif [[ $1 == "rm" ]]; then
    if [[ $2 != "." ]]; then
        podman kill "$2" 2> /dev/null
        podman rm "$2" 2> /dev/null
    fi
    [ ! -z "$3" ] && podman rmi "$3"
fi
